openapi: 3.2.0
info:
  title: Common Models Dont Remove API
  description: Common API models
  contact:
    name: 8x8 Inc
    url: https://cpaas.8x8.com
    email: cpaas-support@8x8.com
  termsOfService: https://cpaas.8x8.com/sg/terms-and-conditions/
  version: '1'
servers:
- url: https://cpaas.8x8.com
security:
- apiKey: []
tags:
- name: Common Models Dont Remove
paths:
  /common-models-dont-remove:
    get:
      summary: OAS file for common models, don't remove, don't publish!
      responses:
        '200':
          description: OAS file for common models, don't remove, don't publish!
      tags:
      - Common Models Dont Remove
components:
  securitySchemes:
    apiKey:
      type: http
      scheme: bearer
      description: '* 8x8 SMS API accepts an **ApiKey Bearer Token** authentication method.


        * You can generate  tokens from your customer portal  [https://connect.8x8.com/](https://connect.8x8.com/)


        * You need to include the following header in your requests: `Authorization: Bearer {apiKey}`


        > **Note**: Replace the `{apiKey}` placeholder with the key generated from the customer portal.

        ---

        If you haven''t created your account yet, please go to 8x8 website [https://connect.8x8.com](https://connect.8x8.com) to sign up.

        '
