{
  "openapi": "3.0.0",
  "info": {
    "title": "8x8 Contact Center Chat API",
    "description": "Integration with the 8x8 Contact Center (CC) Chat API enables you to:\n* Respond in real time to your customer's chat inquiries\n* Initiate chat conversations between your customers and agents\n* Quickly access customer account information in order to better facilitate and enhance your agent's chat session\n* Allocate your company's resources to best address customer chat requirements\n* Review conversation information between your customer and the chat message receiving bot\[...]",
    "contact": { "email": "cc-cluj-oncall@8x8.com" },
    "version": "2.0"
  },
  "servers": [{ "url": "https://api.8x8.com" }],
  "tags": [
    {
      "name": "Authentication",
      "description": "Creates access tokens for endpoint access."
    },
    { "name": "Info", "description": "General information about the API." },
    {
      "name": "WebHooks",
      "description": "Enables webhook definitions that can be associated to channels."
    },
    {
      "name": "JwkKeys",
      "description": "An API that offers JWK public key access to customers."
    },
    {
      "name": "Channels",
      "description": "Enables ChatAPI channel registration and association with a webhook containing channel."
    },
    {
      "name": "Conversations",
      "description": "Provides Contact Center interaction capabilities."
    }
  ],
  "paths": {
    "/oauth/v2/token": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Creates a new access token that can be used for API access.",
        "description": "Creates a new access token that can be used for API access.",
        "operationId": "createaccesstoken",
        "security": [{ "8x8APIBasic": ["basic"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/web-hooks": {
      "get": {
        "tags": ["WebHooks"],
        "summary": "Retrieves all customer webhooks based on the associated token information.",
        "description": "Retrieves all customer webhooks based on the associated token information.",
        "operationId": "getwebhooks",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.webhooks.read"] }]
      },
      "post": {
        "tags": ["WebHooks"],
        "summary": "Creates a new customer webhook.",
        "description": "Creates a new customer webhook.",
        "operationId": "createwebhook",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.webhooks.write"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/web-hooks/{web-hook-id}": {
      "get": {
        "tags": ["WebHooks"],
        "summary": "Get webhook by Id.",
        "description": "Retrieves the webhook by the provided Id.",
        "operationId": "getwebhookbyid",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.webhooks.read"] }]
      },
      "put": {
        "tags": ["WebHooks"],
        "summary": "Updates the full webhook resource by Id.",
        "description": "Updates the full webhook resource by Id.",
        "operationId": "updatewebhook",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.webhooks.write"] }]
      },
      "delete": {
        "tags": ["WebHooks"],
        "summary": "Deletes the webhook by Id.",
        "description": "Deletes the webhook by Id.",
        "operationId": "deletewebhookbyid",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.webhooks.write"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/web-hooks/verify": {
      "post": {
        "tags": ["WebHooks"],
        "summary": "The endpoint used to validate that the webhook is working and reachable.",
        "description": "Validates the webhook URL endpont from the connectivity point-of-view by sending a hello message and a 2xx success status code.",
        "operationId": "verifywebhook",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.webhooks.read"] }]
      }
    },
    "/vcc/{region}/chat/v2/jwk/{jwk-id}/public": {
      "get": {
        "tags": ["JwkKeys"],
        "summary": "Returns the public JWK.",
        "description": "Returns the public JWK that can be used to validate the message signature.",
        "operationId": "getjwkpublickey"
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/channels": {
      "get": {
        "tags": ["Channels"],
        "summary": "Retrieves all customer Chat API channels.",
        "description": "Retrieves all customer Chat API channels based on the provided access token information.",
        "operationId": "getchatapichannels",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.channels.read"] }]
      },
      "post": {
        "tags": ["Channels"],
        "summary": "Creates a channel.",
        "description": "Create a new channel for a customer.",
        "operationId": "createchatapichannel",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.channels.write"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/channels/{channel-id}": {
      "get": {
        "tags": ["Channels"],
        "summary": "Get ChatAPI channel by Id.",
        "description": "Retrieves ChatAPI channel by Id.",
        "operationId": "getchatapichannel",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.channels.read"] }]
      },
      "put": {
        "tags": ["Channels"],
        "summary": "Update ChatAPI channel by Id.",
        "description": "Update ChatAPI channel by Id.",
        "operationId": "updatechatapichannel",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.channels.write"] }]
      },
      "delete": {
        "tags": ["Channels"],
        "summary": "Delete ChatAPI channel by Id.",
        "description": "Deletes ChatAPI channel by the provided Id.",
        "operationId": "deletechatapichannelbyid",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.channels.write"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/conversations": {
      "get": {
        "tags": ["Conversations"],
        "summary": "Returns all conversations belonging to the customer.",
        "description": "Returns a list of all conversations belonging to the customer that comply with the provided filters.",
        "operationId": "getcctransactions",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.conversations.read"] }]
      },
      "post": {
        "tags": ["Conversations"],
        "summary": "Creates a new conversation.",
        "description": "Creates a new transaction in the Contact Center and returns a conversation Id as an identifier that can be used later on to send messages to agent and also close the ongoing transaction.",
        "operationId": "createcctransaction",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.conversations.write"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/conversations/{conversation-id}": {
      "get": {
        "tags": ["Conversations"],
        "summary": "Retrieves conversation details.",
        "description": "Retrieves conversation details.",
        "operationId": "getcctransaction",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.conversations.read"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/conversations/{conversation-id}/participants": {
      "get": {
        "tags": ["Conversations"],
        "summary": "Retrieve the conversation participants.",
        "description": "Retrieves all the participants that joined during the lifespan of the conversation.",
        "operationId": "getparticipantsforcctransaction",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.conversations.read"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/conversations/{conversation-id}/participants/customer": {
      "delete": {
        "tags": ["Conversations"],
        "summary": "Customers leaves conversation.",
        "description": "When customers leave a conversation. It translates to a current interaction that is being terminated by the customer.",
        "operationId": "customerparticipantleavecctransaction",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.conversations.write"] }]
      }
    },
    "/vcc/{region}/chat/v2/tenant/{tenant-id}/conversations/{conversation-id}/messages": {
      "get": {
        "tags": ["Conversations"],
        "summary": "Retrieves the conversation messages.",
        "description": "Retrieves the conversation messages that took place during the lifepan of the conversation.",
        "operationId": "getmessagesforcctransaction",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.conversations.read"] }]
      },
      "post": {
        "tags": ["Conversations"],
        "summary": "Send a message.",
        "description": "Send a message to a conversation represented by the provided ID.",
        "operationId": "sendmessagetocctransaction",
        "security": [{ "8x8APIBearerToken": ["vcc-chat.conversations.write"] }]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "8x8APIBearerToken": {
        "type": "http",
        "scheme": "bearer",
        "description": "Bearer Token obtained from https://api.8x8.com"
      },
      "8x8APIBasic": {
        "type": "http",
        "scheme": "basic",
        "description": "Bearer Token obtained from https://api.8x8.com"
      }
    }
  }
}
